### ISSUE TITLE
Error weather parser

### ISSUE THREAD

**Issue by jsvtrlvrslv** [adriaanjelle/JDWS-03#1]
Access Denied
You don't have permission to access "http://api.weather.com/v3/aggcommon/v3-wx-observations-current;v3-wx-forecast-daily-15day?" on this server.
Maybe API change URL?

**Comment by jsvtrlvrslv** [comment]
> Access Denied You don't have permission to access "http://api.weather.com/v3/aggcommon/v3-wx-observations-current;v3-wx-forecast-daily-15day?" on this server. Maybe API change URL?

https://github.com/adriaanjelle/JDWS-03/blob/9a8a77f1da58323428c614e4f8287855dadacc7f/Files/%40Resources/WeatherParser.inc#L2

API Key erro. Soluction:
WeatherAPIKey=71f92ea9dd2f4790b92ea9dd2f779061

**Comment by adriaanjelle** [comment]
I'll take a look at it!

**Comment by adriaanjelle** [comment]
The issue has been resolved, expect a fix in the coming update.
